package com.openmemo.opmback.mapper.authority;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * authority.id
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * authority.customer_id
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * authority.rolename
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column authority.id
     *
     * @return the value of authority.id
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column authority.customer_id
     *
     * @return the value of authority.customer_id
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column authority.customer_id
     *
     * @param customerId the value for authority.customer_id
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column authority.rolename
     *
     * @return the value of authority.rolename
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column authority.rolename
     *
     * @param rolename the value for authority.rolename
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
}
