package com.openmemo.opmback.mapper.authority;

import com.openmemo.opmback.mapper.authority.Authority;
import com.openmemo.opmback.mapper.authority.AuthorityExample;
import com.openmemo.opmback.mapper.post.Post;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    long countByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int deleteByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int insert(Authority row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int insertSelective(Authority row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    List<Authority> selectByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    Authority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByExampleSelective(@Param("row") Authority row, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByExample(@Param("row") Authority row, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByPrimaryKeySelective(Authority row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByPrimaryKey(Authority row);

    int insertCustom(Authority row);
}