package com.openmemo.opmback.mapper.authority;

import com.openmemo.opmback.mapper.authority.AuthorityExample;
import com.openmemo.opmback.mapper.authority.AuthorityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    long countByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    int deleteByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    int deleteByPrimaryKey(AuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    int insert(AuthorityKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    int insertSelective(AuthorityKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    List<AuthorityKey> selectByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    int updateByExampleSelective(@Param("row") AuthorityKey row, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    int updateByExample(@Param("row") AuthorityKey row, @Param("example") AuthorityExample example);
}