package com.openmemo.opmback.mapper.authority;

public class AuthorityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.customer_id
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.rolename
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.customer_id
     *
     * @return the value of authority.customer_id
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.customer_id
     *
     * @param customerId the value for authority.customer_id
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.rolename
     *
     * @return the value of authority.rolename
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.rolename
     *
     * @param rolename the value for authority.rolename
     *
     * @mbg.generated Thu Feb 15 01:48:13 JST 2024
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
}