package com.openmemo.opmback.mapper.post;

import com.openmemo.opmback.mapper.post.Post;
import com.openmemo.opmback.mapper.post.PostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    long countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int insert(Post row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int insertSelective(Post row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByExampleSelective(@Param("row") Post row, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByExample(@Param("row") Post row, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByPrimaryKeySelective(Post row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * post
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByPrimaryKey(Post row);

    int updateByPrimaryKeyCustom(Post row);

    int insertCustom(Post row);

    List<Post> selectByExampleCustom(PostExample example);
}
