package com.openmemo.opmback.mapper.customer;

import com.openmemo.opmback.mapper.customer.Customer;
import com.openmemo.opmback.mapper.customer.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int insert(Customer row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int insertSelective(Customer row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    Customer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByExampleSelective(@Param("row") Customer row,
            @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByExample(@Param("row") Customer row, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByPrimaryKeySelective(Customer row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * customer
     *
     * @mbg.generated Sun Dec 03 13:07:23 JST 2023
     */
    int updateByPrimaryKey(Customer row);

    int save(Customer row);
}
